### ISSUE TITLE
App crash while attempting to share a Haven Log

### ISSUE THREAD

**Issue by archie94** [guardianproject/haven#181]
Hello, on my device the app is crashing with error log

    FATAL EXCEPTION: main
                                                 Process: org.havenapp.main, PID: 4903
                                                 java.lang.NullPointerException
                                                     at java.io.File.<init>(File.java:262)
                                                     at org.havenapp.main.ui.EventActivity.shareEvent(EventActivity.java:146)
                                                     at org.havenapp.main.ui.EventActivity.access$000(EventActivity.java:24)
                                                     at org.havenapp.main.ui.EventActivity$1.onClick(EventActivity.java:62)
                                                     at android.view.View.performClick(View.java:5619)
                                                     at android.view.View$PerformClick.run(View.java:22295)
                                                     at android.os.Handler.handleCallback(Handler.java:754)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:163)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6237)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

I am using a Redmi Note 4, Android Version 7.0 NRD90M, MIUI version : 9.0.5.0 (NCFMIEI)

**Comment by archie94** [comment]
On further investigation, the crash appears to be caused by null `mPath` in `EventTrigger` instances. Both the events were Bump (Accelerometer) events 

![haven_scr_2](https://user-images.githubusercontent.com/12955150/34494217-65281ac8-f015-11e7-9adf-6d989e77f27a.jpg)

![haven_scr_1](https://user-images.githubusercontent.com/12955150/34494209-5e27d042-f015-11e7-8f53-98df02301ca9.jpg)

![haven_crash_2](https://user-images.githubusercontent.com/12955150/34494129-e9b49826-f014-11e7-9437-4343a83b4038.png)

![haven_crash_1](https://user-images.githubusercontent.com/12955150/34494131-ea144122-f014-11e7-9a63-650fc3ed956c.png)
