### ISSUE TITLE
Back button causes active session crash on resume

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#248]
### Prerequisites

* [x] Reproduced issue on both device & simulator?
* [x] Running the latest build/release? 
* [x] Fresh uninstall/install of Haven & Orbot from F-Droid?

### Description
Pressing back button opens logs; The button to activate the session then causes the app to crash. 

### Steps to Reproduce

1. Activate session
2. Press device back button
3. Press button (lower right fab)
4. Crashes

**Expected:**

* Return to activity monitor preview

**Actual behavior:**

* Crash
* Camera is used after being released or bind handler is leaked

Repo: F-Droid
Version: beta 112
Device: Android 5.1 Nexus 4
Related Issues/commits: #245 produces the same behavior. #238 

### Trace pseudocode:

`Preview -> MonitorActivity.doCancel()  > ListActivity > CRASH`

**Comment by fat-tire** [comment]
```
01-29 15:04:27.451  7162  7162 E AndroidRuntime: Process: org.havenapp.main, PID: 7162
01-29 15:04:27.451  7162  7162 E AndroidRuntime: java.lang.RuntimeException: getParameters failed (empty parameters)
01-29 15:04:27.451  7162  7162 E AndroidRuntime: 	at android.hardware.Camera.native_getParameters(Native Method)
01-29 15:04:27.451  7162  7162 E AndroidRuntime: 	at android.hardware.Camera.getParameters(Camera.java:1960)
01-29 15:04:27.451  7162  7162 E AndroidRuntime: 	at org.havenapp.main.sensors.motion.Preview$2.onPreviewFrame(Preview.java:245)
01-29 15:04:27.451  7162  7162 E AndroidRuntime: 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1153)`
```

So in `havenapp/main/sensors/motion/Preview.java`, you got:

      final Camera.Size size = cam.getParameters().getPreviewSize();

...which is calling Android's `Camera` class method `getParameters()` that calls a native method `active_getParameters()` which returns the empty parameters.

Instead of doing the responsible thing and figuring out why the native call is coming up empty, I tried just catching the exception and it seemed to work.... in the emulator at least.  Dunno if it broke anything, but if someone wants to test this and create a PR, that's fine by me.

```
diff --git a/src/main/java/org/havenapp/main/sensors/motion/Preview.java b/src/main/java/org/havenapp/main/sensors/motion/Preview.java
index 8f08c26..b2e016d 100644
--- a/src/main/java/org/havenapp/main/sensors/motion/Preview.java
+++ b/src/main/java/org/havenapp/main/sensors/motion/Preview.java
@@ -242,7 +242,12 @@ public class Preview extends SurfaceView implements SurfaceHolder.Callback {
 
                     public void onPreviewFrame(byte[] data, Camera cam) {
 
-                        final Camera.Size size = cam.getParameters().getPreviewSize();
+                        Camera.Size size;
+                        try {
+                            size = cam.getParameters().getPreviewSize();
+                        } catch(RuntimeException e) {
+                            return;
+                        }
                         if (size == null) return;
                         long now = System.currentTimeMillis();
                         if (now < Preview.this.lastTimestamp + PREVIEW_INTERVAL)
```

**Comment by lukeswitz** [comment]
Thank you, testing this now!

**Comment by lukeswitz** [comment]
Still crashes: 
```
MonitorActivity has leaked ServiceConnection org.havenapp.main.sensors.motion.Preview$1@896abc3 that was originally bound here
                                                                   android.app.ServiceConnectionLeaked: Activity org.havenapp.main.MonitorActivity has leaked ServiceConnection org.havenapp.main.sensors.motion.Preview$1@896abc3 that was originally bound here
                                                                       at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
                                                                       at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
                                                                       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1774)
                                                                       at android.app.ContextImpl.bindService(ContextImpl.java:1757)
                                                                       at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
                                                                       at org.havenapp.main.sensors.motion.Preview.<init>(Preview.java:127)
                                                                       at org.havenapp.main.ui.CameraFragment.initCamera(CameraFragment.java:85)
                                                                       at org.havenapp.main.ui.CameraFragment.onResume(CameraFragment.java:59)
                                                                       at android.support.v4.app.Fragment.performResume(Fragment.java:2308)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3191)
                                                                       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
                                                                       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:482)
                                                                       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:471)
                                                                       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
                                                                       at android.app.Activity.performResume(Activity.java:6089)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by lukeswitz** [comment]
It was a combination of things: mainly the camera got itself lost when jumping into the settings activity from the monitor. 
* Added catch for camera size: 700ecce87403f58c7202d9e51306024d475c3ae0 submitted above by @fat-tire 
* #245 Fix surface change on settings view, handle 'View Logs' correctly: 4d0ce439d2e945d8d0809169d63d5311c0000c28
* Added catch for null values on save: 78cc43eaf1d6b6583985d47d1fd1c568c0aaabad

Please let me know if any of these look good enough for a PR
