### ISSUE TITLE
Crash on MonitorActivity Resume

### ISSUE THREAD

**Issue by archie94** [guardianproject/haven#313]
Crashlog

```
/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.havenapp.main, PID: 26670
    java.lang.RuntimeException: Unable to resume activity {org.havenapp.main/org.havenapp.main.MonitorActivity}: java.lang.IllegalArgumentException: Service not registered: org.havenapp.main.sensors.motion.Preview$1@dff8af1
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3450)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
     Caused by: java.lang.IllegalArgumentException: Service not registered: org.havenapp.main.sensors.motion.Preview$1@dff8af1
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1298)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1483)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
        at org.havenapp.main.sensors.motion.Preview.stopCamera(Preview.java:402)
        at org.havenapp.main.ui.CameraFragment.stopCamera(CameraFragment.java:68)
        at org.havenapp.main.ui.CameraFragment.resetCamera(CameraFragment.java:75)
        at org.havenapp.main.ui.CameraFragment.onResume(CameraFragment.java:62)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2387)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3215)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
        at android.app.Activity.performResume(Activity.java:6815)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3427)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6165) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 
```

**Comment by lukeswitz** [comment]
To replicate: 
- MonitorActivity > Settings > Camera Sensitivity > Settings > MonitorActivity

**Comment by n8fr8** [comment]
Should be fixed in 0.2.0 alpha 2

**Comment by n8fr8** [comment]
Appreciate the logs!

**Comment by lukeswitz** [comment]
The least I could do; Impressive sprint! This is looking excellent
