### ISSUE TITLE
Crash on Nexus 5 running LinageOS

### ISSUE THREAD

**Issue by micahflee** [guardianproject/haven#46]
I'm using a Nexus 5 with LineageOS, and Haven 0.0.18.

As soon as I'm done clicking through the onboarding wizard, the app crashes. Here's a screenshot and the logcat logs:

![signal-2017-12-18-144150](https://user-images.githubusercontent.com/156128/34133145-fe0b3f6e-e407-11e7-9579-6990bdae74fb.png)

```
12-18 15:25:14.173  1782  1913 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
12-18 15:25:18.820  2294  3471 I ActivityManager: START u0 {cmp=info.guardianproject.phoneypot/.MonitorActivity} from uid 10078 on display 0
12-18 15:25:18.910  8676  8676 I CameraFragment: Sensitivity set to High
12-18 15:25:19.037  1789  2729 I CameraService: CameraService::connect call (PID -1 "info.guardianproject.phoneypot", camera ID 1) for HAL version default and Camera API version 1
12-18 15:25:19.038  1789  2729 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0
12-18 15:25:19.049  1789  8730 D NuPlayerDriver: notifyListener_l(0xb5d2b080), (1, 0, 0), loop setting(0, 0)
12-18 15:25:19.066  1789  8732 D NuPlayerDriver: notifyListener_l(0xb5d2baa0), (1, 0, 0), loop setting(0, 0)
12-18 15:25:19.082  1789  8734 D NuPlayerDriver: notifyListener_l(0xb5d2ba40), (1, 0, 0), loop setting(0, 0)
12-18 15:25:19.082  1789  2729 I Camera2ClientBase: Camera 1: Opened. Client: info.guardianproject.phoneypot (PID 8676, UID 10078)
12-18 15:25:19.085  1789  2729 D mm-camera-intf: mm_camera_open: dev name = /dev/video2, cam_idx = 2
12-18 15:25:19.085  1792  1792 I mm-camera-sensor: module_sensor_start_session:584 session 2
12-18 15:25:19.304  1792  1792 I mm-camera-sensor: module_sensor_init_session:478 ois device is not supported
12-18 15:25:19.304  1792  1792 I mm-camera-sensor: 
12-18 15:25:19.306  1792  1792 I mm-camera: gyro_module_start_session: Enter
12-18 15:25:19.306  1792  1792 I mm-camera: gyro_module_start_session: Init DSPS
12-18 15:25:19.306  1792  1792 E mm-camera: Failed to open sensor1 port
12-18 15:25:19.306  1792  1792 I mm-camera: gyro_module_start_session: dsps_proc_init() failed
12-18 15:25:19.306  1792  1792 I mm-camera: gyro_module_get_port: Exit failure
12-18 15:25:19.306  1792  1792 I mm-camera: cpp_module_start_session:352, info: starting session 2
12-18 15:25:19.327  1792  1792 I mm-camera: cpp_module_start_session:433, info: cpp_thread created.
12-18 15:25:19.328  1792  1792 I mm-camera: cpp_module_start_session:436, info: session 2 started.
12-18 15:25:19.328  1792  1792 I mm-camera: c2d_module_start_session:246, info: starting session 2
12-18 15:25:19.328  1792  8736 I mm-camera: cpp_thread_func:55: cpp_thread entering the polling loop...
12-18 15:25:19.328  1792  8737 I mm-camera: c2d_thread_func:39: c2d_thread entering the polling loop...
12-18 15:25:19.328  1792  1792 I mm-camera: c2d_module_start_session:284, info: c2d_thread created.
12-18 15:25:19.330  1792  1792 I mm-camera: c2d_module_start_session:306, info: session 2 started.
12-18 15:25:19.331  1792  1792 I mm-camera-sensor: module_module_set_session_data:2667 max delay 2 report dSelay 1
12-18 15:25:19.331  1792  1792 D mm-camera: module_faceproc_set_session_data:1987] Per frame control 2 1
12-18 15:25:19.331  1789  2729 D mm-camera-intf: mm_camera_open:  opened, break out while loop
12-18 15:25:19.332  3193  3204 E ANDR-PERF-LOCK: Failed to apply optimization for resource: 4 level: 0
12-18 15:25:19.335  1789  2729 I Camera2-Parameters: Camera 1: Disabling ZSL mode
12-18 15:25:19.335  1789  2729 I Camera2-Parameters: initialize: allowZslMode: 0 slowJpegMode 0
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 1280 height: 960
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 1280 height: 768
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 1280 height: 720
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 1024 height: 768
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 800 height: 600
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 800 height: 480
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 720 height: 480
12-18 15:25:19.341  8676  8676 I SurfaceView: width: 640 height: 480
12-18 15:25:19.341  8676  8676 I SurfaceView: selected width: 640 selected height: 480
12-18 15:25:19.342  1789  1789 E Camera2-Parameters: set: Requested preview FPS range 15 - 30 is not supported
12-18 15:25:19.346  8676  8676 D AndroidRuntime: Shutting down VM
12-18 15:25:19.347  8676  8676 E AndroidRuntime: FATAL EXCEPTION: main
12-18 15:25:19.347  8676  8676 E AndroidRuntime: Process: info.guardianproject.phoneypot, PID: 8676
12-18 15:25:19.347  8676  8676 E AndroidRuntime: java.lang.RuntimeException: setParameters failed
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.hardware.Camera.native_setParameters(Native Method)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.hardware.Camera.setParameters(Camera.java:2015)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at info.guardianproject.phoneypot.sensors.motion.Preview.surfaceCreated(Preview.java:228)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-18 15:25:19.347  8676  8676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-18 15:25:19.349  2294  3348 W ActivityManager:   Force finishing activity info.guardianproject.phoneypot/.MonitorActivity
```

**Comment by n8fr8** [comment]
Will use one of the provided ranges indicated by the camera...

**Comment by micahflee** [comment]
Awesome, I confirmed that Haven 0.0.20 fixes this
