### ISSUE TITLE
App crashes with SQLiteException

### ISSUE THREAD

**Issue by itssmutnuri** [guardianproject/haven#63]
Found that the app crashes with a SQLiteException. Was able to reproduce it by leaving it in the activate mode for a while. Relaunching the app gave the below FATAL EXCEPTION. Please refer to the log file for a full version. Not sure if it was an error from my end.

`12-23 02:49:11.123 14971-14971/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.havenapp.main, PID: 14971
                                                                   android.database.sqlite.SQLiteException: no such table: EVENT (code 1): , while compiling: INSERT OR REPLACE  INTO EVENT(ID,M_START_TIME) VALUES (?,?)
                                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1470)
                                                                       at com.orm.SugarRecord.save(SugarRecord.java:280)
                                                                       at com.orm.SugarRecord.save(SugarRecord.java:416)
                                                                       at org.havenapp.main.service.MonitorService.alert(MonitorService.java:247)
                                                                       at org.havenapp.main.service.MonitorService$MessageHandler.handleMessage(MonitorService.java:92)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

[HavenLogcat.log](https://github.com/guardianproject/haven/files/1583512/HavenLogcat.log)

**Comment by n8fr8** [comment]
Looks like the database wasn't properly init'd. Did you install from APK, or from your own compiled source?

**Comment by itssmutnuri** [comment]
@n8fr8 Both. It crashed when I installed beta from Play Store, so I wanted to build from source, and it repeated.  I've not checked the logs for the earlier crash.

**Comment by TheDorkKnightRises** [comment]
@n8fr8 I am getting the same SQLiteException on my primary device running Android 8.1 every time I install my own source-compiled version. The same build works fine on my 4.4.2 devices or when I install from Play Store on that same device.

**Comment by Peng-Da** [comment]
I met the same exception.

**Comment by opticod** [comment]
Currently the Sugar is not supported by `Instant Run` feature of Android Studio 2.2+, so we are facing some SQLExceptions. Try turning the `Instant Run` feature off.

**Comment by lingyunzhu** [comment]
try using “SugarRecord.save(mLastEvent);”  instead of  “mLastEvent.save();” in MonitorService.java

**Comment by pk-development** [comment]
I'd the same issue every time a detection event happened the app would crash, I disabled instant run uninstalled app, built and installed and stilled crashed. Long story short I ended up seeing I did not have SMS permissions in another crash so I had to manually go to phone>Settings>Apps to turn on Telephony and SMS. Android 7.0, not sure if this is a common issue because the app never asked me for these 2 permissions in the setup phase.

**Comment by n8fr8** [comment]
Did you enable the sms notification sending, by entering a phone number?

**Comment by pk-development** [comment]
@n8fr8 I just uninstalled and tested again with initial setup, clicked save number and was never asked for permission.

**Comment by jasonhartley** [comment]
I've only tried building from source and I have the same exception.
* Happens on Android 7.0 (Samsung S7) and 8.1.0 (Pixel)
* I have all permissions turned on.
* Instant run in Android Studio is off
* I tried SugarRecord.save(mLastEvent) as @lingyunzhu suggested
A non-fatal version of the same error also happens in ListActivity#onCreate when Event.count(Event.class) is called.

**Comment by n8fr8** [comment]
Any improvement with the latest code?

**Comment by pjohnson-carecloud** [comment]
hi, is sugar not supporting instant run yet?

**Comment by n8fr8** [comment]
No. We have removed support for Sugar anyhow, and moved to Rooms Persistance.
