### ISSUE TITLE
Crash on API levels 20 and below

### ISSUE THREAD

**Issue by TheDorkKnightRises** [guardianproject/haven#90]
App crashes at launch on API<=20, as it is unable to resolve a resource reference.
The referenced resource is a part of the app intro library but does not seem to be resolved on lower API levels. A simple fix would be to manually include the drawable in our module's res/drawables. I am in the process of submitting a PR with this fix.

Log:
```
12-24 01:47:09.765 27361-27361/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.havenapp.main, PID: 27361
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.havenapp.main/org.havenapp.main.ListActivity}: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_forward_white.xml from drawable resource ID #0x7f08006a
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                       at android.os.Looper.loop(Looper.java:193)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_forward_white.xml from drawable resource ID #0x7f08006a
                                                                       at android.content.res.Resources.loadDrawable(Resources.java:2152)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:710)
                                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                                                                       at org.havenapp.main.ListActivity.onCreate(ListActivity.java:127)
                                                                       at android.app.Activity.performCreate(Activity.java:5343)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                       at android.os.Looper.loop(Looper.java:193) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
                                                                       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                                       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                                       at android.content.res.Resources.loadDrawable(Resources.java:2148)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:710) 
                                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                                                                       at org.havenapp.main.ListActivity.onCreate(ListActivity.java:127) 
                                                                       at android.app.Activity.performCreate(Activity.java:5343) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                       at android.os.Looper.loop(Looper.java:193) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by fat-tire** [comment]
fixed in #62 too.  I had issues with the XML being stripped out by AS (latest) so went w/a different solution.
